load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = ["booking.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/booking/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//code/booking/controller",
        "//code/booking/entity",
        "//code/booking/store",
        "//code/booking/util",
        "//gen/idl/booking",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "handler_test",
    srcs = ["booking_test.go"],
    embed = [":handler"],
    deps = [
        "//code/booking/entity",
        "//code/booking/store",
        "//gen/idl/booking",
        "//gen/mocks/booking/controller",
        "@com_github_golang_mock//gomock",
        "@com_github_stretchr_testify//assert",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
