load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = ["resource.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/resource/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//code/resource/controller",
        "//code/resource/entity",
        "//code/resource/store",
        "//code/resource/util",
        "//gen/idl/resource",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "handler_test",
    srcs = ["resource_test.go"],
    embed = [":handler"],
    deps = [
        "//code/resource/entity",
        "//code/resource/store",
        "//gen/idl/resource",
        "//gen/mocks/resource/controller",
        "@com_github_golang_mock//gomock",
        "@com_github_stretchr_testify//assert",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
