load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = ["user.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/identity/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//code/identity/controller",
        "//code/identity/entity",
        "//code/identity/store",
        "//code/identity/util",
        "//gen/idl/identity",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "handler_test",
    srcs = ["user_test.go"],
    embed = [":handler"],
    deps = [
        "//code/identity/entity",
        "//gen/idl/identity",
        "//gen/mocks/identity/controller",
        "@com_github_golang_mock//gomock",
        "@com_github_stretchr_testify//assert",
    ],
)
