load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = ["handler.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/api-gateway/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//code/api-gateway/client",
        "//code/api-gateway/middleware",
        "//code/api-gateway/util",
        "//gen/idl/booking",
        "//gen/idl/identity",
        "//gen/idl/resource",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "handler_test",
    srcs = ["handler_test.go"],
    embed = [":handler"],
    deps = [
        "//code/api-gateway/middleware",
        "//gen/idl/identity",
        "//gen/mocks/api_gateway/client",
        "@com_github_golang_mock//gomock",
        "@com_github_stretchr_testify//assert",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
