load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "smtp",
    srcs = ["smtp.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/booking/mailer/smtp",
    visibility = ["//visibility:public"],
    deps = ["@in_gopkg_gomail_v2//:gomail_v2"],
)

go_test(
    name = "smtp_test",
    srcs = ["smtp_test.go"],
    embed = [":smtp"],
    deps = ["@com_github_stretchr_testify//require"],
)
