load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = ["module.go"],
    data = glob(["*.yaml"]),
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/booking/config",
    visibility = ["//visibility:public"],
    deps = [
        "//code/booking/client",
        "//code/booking/controller",
        "//code/booking/handler",
        "//code/booking/mailer",
        "//code/booking/store",
        "//gen/idl/booking",
        "//pkg/configloader",
        "//pkg/grpcserver",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@org_golang_google_grpc//:grpc",
        "@org_uber_go_fx//:fx",
    ],
)
