load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "store",
    srcs = ["resource.go"],
    importpath = "github.com/PriyanshuTrivedi/nexus-scheduler/code/resource/store",
    visibility = ["//visibility:public"],
    deps = [
        "//code/resource/entity",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)

go_test(
    name = "store_test",
    srcs = ["resource_test.go"],
    embed = [":store"],
    deps = ["@com_github_stretchr_testify//assert"],
)
